### ISSUE TITLE
Combining verbosity level 3 definitions in TeamsNotifyer

### ISSUE THREAD

**Issue by a-vogel** [autopkg/wycomco-recipes#32]
Can the [if loop](https://github.com/autopkg/wycomco-recipes/blob/master/SharedProcessors/MunkiRepoTeamsNotifier.py#L313) for verbosity level 3 be moved to the definition starting in line 325? Or are there implications that need the definitions to be separated?

**Comment by choules** [comment]
The only implication would be a different order in the displayed information. If someone would actually use the high verbosity level, the `name` attribute would be placed next to the `icon path`:

![Screenshot with high verbosity](https://user-images.githubusercontent.com/4222606/224924448-7efb6e6a-d118-4828-8c23-602c3c6db59d.png)

**Comment by a-vogel** [comment]
Is the name attribute needed? We already have the name (and display_name, if different) right to the logo. So this seems to me a redundant information anyway.

**Comment by a-vogel** [comment]
Name attribute is needed if workflow changes to fetch summarizes in json and only send one single message for all apps of the current run at the end. Since we don't use the high verbosity level and no impact is given atm, issue can be closed.
